### ISSUE TITLE
Error with one training file: if feature in self.currentVarianceVectors[minCorrectLabel]: KeyError: None

### ISSUE THREAD

**Issue by dhruvghulati-zz** [andreasvlachos/arow_csc#6]
All my training file is working, apart from one type where the costs in the CSC are directly my APEs in the closed version, for bigrams of the words as the features:

[closed_cost_5_0.0001_0.03_bigrams.txt](https://github.com/andreasvlachos/arow_csc/files/441268/closed_cost_5_0.0001_0.03_bigrams.txt)

```
Traceback (most recent call last):
  File "src/main/arow_claim_csc.py", line 46, in <module>
    cl.train(train_data)
  File "/Users/dhruv/Documents/university/ClaimDetection/src/main/arow.py", line 369, in train
    averagedWeightVectors, updatesLeft)
  File "/Users/dhruv/Documents/university/ClaimDetection/src/main/arow.py", line 303, in _update_parameters
    if feature in self.currentVarianceVectors[minCorrectLabel]:
KeyError: None
```

I'm finding it hard to troubleshoot as this is just 1 out of 50+ files I have trained for development. I tried modifying my cost vectors for each instance so anything which is a `float(inf)` cost is converted to `float(1e10)`, but this doesn't solve the problem. I am unsure what the traceback actually means.

I could obviously ignore this as a wild instance as I have 95% of the all my files training and spitting out predictions, but would be good to see why this is the case.

**Comment by andreasvlachos** [comment]
As far as I can tell, the only way this can happen is if the minCorrectLabel is None, which means either that all correctLabels had score of Inf (unlikely), or that no correctLabel was set for the instance, something that is handled during the initialisation via the _normalize_costs function. Note that the issue is encountered by using code beyond the code available on this repo, thus nor I can reproduce it, nether I am sure it is a problem with the code here.
